Repository AY2425S2-CS2113-T13-1/tp, pull requests merged in 2025-04, with the labels that each got.

#76 fix cookable bug
  src/main/java/commands/CookableRecipesCommand.java
  src/main/java/commands/DeleteCommand.java
  src/main/java/ui/inputparser/Parser.java
  src/test/java/kitchenctrl/CookableRecipesTest.java
Labels: severity.High, type.Bug

#86 Added Javadoc for enhanced documentations
  docs/DeveloperGuide.md
  docs/diagrams/model.png
  docs/diagrams/model.puml
  docs/team/johndoe.md
  docs/team/weiliangng.md
  src/main/java/commands/AddCommand.java
  src/main/java/commands/DeleteCommand.java
  src/main/java/controller/KitchenCTRL.java
Labels: type.Task

#171 Added basic testing for Recipe and InventoryCatalogue
  src/test/java/kitchenctrl/IngredientCatalogueTest.java
  src/test/java/kitchenctrl/RecipeTest.java
Labels: type.Task

#172 Silenced parser to default add new entry on file parsing
  src/main/java/commands/AddCommand.java
  src/main/java/commands/DeleteCommand.java
  src/main/java/commands/EditIngredientCommand.java
  src/main/java/model/catalogue/Catalogue.java
  src/main/java/model/catalogue/IngredientCatalogue.java
  src/main/java/model/catalogue/RecipeBook.java
  src/main/java/storage/CatalogueContentManager.java
  src/main/java/ui/inputparser/ConflictHelper.java
  src/main/java/ui/inputparser/Parser.java
  src/main/java/ui/inputparser/Ui.java
  src/test/java/kitchenctrl/CookableRecipesTest.java
  src/test/java/kitchenctrl/IngredientCatalogueTest.java
  src/test/java/kitchenctrl/LogicTest.java
  src/test/java/kitchenctrl/RecipeBookTest.java
  src/test/java/kitchenctrl/RecipeTest.java
  src/test/java/kitchenctrl/StorageTest.java
  src/test/java/kitchenctrl/UiTest.java
Labels: severity.Medium, type.Bug

#189 Updated UG
  docs/UserGuide.md
Labels: priority.High
